const products = [
  {
    title: "Magnetite",
    category: "MPB",
    price: 89.0,
    img: "./assets/img/1.jpg",
    band: "Scalene",
    year: 2017,
    id: 0,
  },
  {
    title: "Acabou o Chorare",
    category: "Baião",
    price: 66.0,
    img: "./assets/img/2.jpg",
    band: "Novos Baianos",
    year: 1972,
    id: 1,
  },
  {
    title: "Nirvana Discografia",
    category: "Rock",
    price: 50.0,
    img: "./assets/img/3.jpg",
    band: "Nirvava",
    year: 1990,
    id: 2,
  },
  {
    title: "Both Sides",
    category: "Rock",
    price: 22.0,
    img: "./assets/img/4.jpg",
    band: "Phil Collins",
    year: 1993,
    id: 3,
  },
  {
    title: "O Sol e a Lua",
    category: "Brasileira",
    price: 60.0,
    img: "./assets/img/sol.jpg",
    band: "Pequeno Cidadão",
    year: 2012,
    id: 4,
  },
  {
    title: "A Banda",
    category: "Brasileira",
    price: 98.0,
    img: "./assets/img/a banda.jpg",
    band: "Chico Buarque",
    year: 1966,
    id: 5,
  },
];

